name: Release

on:
  push:
    branches:
      - develop
      - main
      - production

permissions:
  contents: write

jobs:
  release:
    name: "Create Release"
    runs-on: ubuntu-latest
    steps:
      - uses: alleyinteractive/action-release@feature
